//
//  UIColor+ALTRUUSAdditions.m
//
//  Generated by Zeplin on 7/12/16.
//  Copyright (c) 2016 __MyCompanyName__. All rights reserved. 
//

#import "UIColor+ALTRUUSAdditions.h"

@implementation UIColor (ALTRUUSAdditions)

+ (UIColor *)altruus_darkSkyBlueColor {
	return [UIColor colorWithRed:74.0f / 255.0f green:144.0f / 255.0f blue:226.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)altruus_veryLightBlueColor {
	return [UIColor colorWithRed:234.0f / 255.0f green:244.0f / 255.0f blue:255.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)altruus_lightBlueGreyColor {
	return [UIColor colorWithRed:175.0f / 255.0f green:202.0f / 255.0f blue:229.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)altruus_duckEggBlueColor {
	return [UIColor colorWithRed:248.0f / 255.0f green:251.0f / 255.0f blue:254.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)altruus_barbiePinkColor {
	return [UIColor colorWithRed:255.0f / 255.0f green:50.0f / 255.0f blue:130.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)altruus_paleMauveColor {
	return [UIColor colorWithRed:253.0f / 255.0f green:223.0f / 255.0f blue:240.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)altruus_cloudyBlueColor {
	return [UIColor colorWithRed:171.0f / 255.0f green:187.0f / 255.0f blue:207.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)altruus_hospitalGreenColor {
	return [UIColor colorWithRed:135.0f / 255.0f green:226.0f / 255.0f blue:139.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)altruus_duckEggBlueTwoColor {
	return [UIColor colorWithRed:225.0f / 255.0f green:250.0f / 255.0f blue:226.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)altruus_perrywinkleColor {
	return [UIColor colorWithRed:169.0f / 255.0f green:134.0f / 255.0f blue:236.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)altruus_watermelonColor {
	return [UIColor colorWithRed:251.0f / 255.0f green:77.0f / 255.0f blue:93.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)altruus_paleColor {
	return [UIColor colorWithRed:254.0f / 255.0f green:247.0f / 255.0f blue:209.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)altruus_bluegreyColor {
	return [UIColor colorWithRed:140.0f / 255.0f green:162.0f / 255.0f blue:182.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)altruus_mediumBlueColor {
	return [UIColor colorWithRed:49.0f / 255.0f green:115.0f / 255.0f blue:191.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)altruus_freshGreenColor {
	return [UIColor colorWithRed:67.0f / 255.0f green:210.0f / 255.0f blue:74.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)altruus_lightishGreenColor {
	return [UIColor colorWithRed:102.0f / 255.0f green:227.0f / 255.0f blue:108.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)altruus_skyBlueColor {
	return [UIColor colorWithRed:116.0f / 255.0f green:180.0f / 255.0f blue:255.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)altruus_goldenYellowColor {
	return [UIColor colorWithRed:250.0f / 255.0f green:211.0f / 255.0f blue:27.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)altruus_perrywinkleTwoColor {
	return [UIColor colorWithRed:160.0f / 255.0f green:122.0f / 255.0f blue:234.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)altruus_whiteColor {
	return [UIColor colorWithWhite:255.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)altruus_darkSkyBlue10Color {
	return [UIColor colorWithRed:73.0f / 255.0f green:143.0f / 255.0f blue:226.0f / 255.0f alpha:0.1f];
}

+ (UIColor *)altruus_darkSkyBlue4Color {
	return [UIColor colorWithRed:73.0f / 255.0f green:143.0f / 255.0f blue:226.0f / 255.0f alpha:0.04f];
}

+ (UIColor *)altruus_bluegreyTwoColor {
	return [UIColor colorWithRed:149.0f / 255.0f green:170.0f / 255.0f blue:194.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)altruus_slateColor {
	return [UIColor colorWithRed:63.0f / 255.0f green:80.0f / 255.0f blue:99.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)altruus_darkGreyBlueColor {
    return [UIColor colorWithRed:49.0f / 255.0f green:80.0f / 255.0f blue:115.0f / 255.0f alpha:1.0f];
}

@end
