//
//  UIColor+ALTRUUSAdditions.h
//
//  Generated by Zeplin on 7/12/16.
//  Copyright (c) 2016 __MyCompanyName__. All rights reserved. 
//

#import <UIKit/UIKit.h>

@interface UIColor (ALTRUUSAdditions)

+ (UIColor *)altruus_darkSkyBlueColor;
+ (UIColor *)altruus_veryLightBlueColor;
+ (UIColor *)altruus_lightBlueGreyColor;
+ (UIColor *)altruus_duckEggBlueColor;
+ (UIColor *)altruus_barbiePinkColor;
+ (UIColor *)altruus_paleMauveColor;
+ (UIColor *)altruus_cloudyBlueColor;
+ (UIColor *)altruus_hospitalGreenColor;
+ (UIColor *)altruus_duckEggBlueTwoColor;
+ (UIColor *)altruus_perrywinkleColor;
+ (UIColor *)altruus_watermelonColor;
+ (UIColor *)altruus_paleColor;
+ (UIColor *)altruus_bluegreyColor;
+ (UIColor *)altruus_mediumBlueColor;
+ (UIColor *)altruus_freshGreenColor;
+ (UIColor *)altruus_lightishGreenColor;
+ (UIColor *)altruus_skyBlueColor;
+ (UIColor *)altruus_goldenYellowColor;
+ (UIColor *)altruus_perrywinkleTwoColor;
+ (UIColor *)altruus_whiteColor;
+ (UIColor *)altruus_darkSkyBlue10Color;
+ (UIColor *)altruus_darkSkyBlue4Color;
+ (UIColor *)altruus_bluegreyTwoColor;
+ (UIColor *)altruus_slateColor;
+ (UIColor *)altruus_darkGreyBlueColor;

@end
