//
//  UIFont+ALTRUUSAdditions.m
//
//  Generated by Zeplin on 6/21/16.
//  Copyright (c) 2016 __MyCompanyName__. All rights reserved. 
//

#import "UIFont+ALTRUUSAdditions.h"

@implementation UIFont (ALTRUUSAdditions)

+ (UIFont *)altruus_styleMediumFont {
    return [UIFont systemFontOfSize:17.0f weight:UIFontWeightMedium];
}

+ (UIFont *)altruus_styleRegularFont {
    return [UIFont systemFontOfSize:14.0f weight:UIFontWeightRegular];
}

+ (UIFont *)altruus_menuMediumFont {
    return [UIFont systemFontOfSize:11.0f weight:UIFontWeightMedium];
}

+ (UIFont *)altruus_menuSemiBoldFont {
    return [UIFont systemFontOfSize:14.0f weight:UIFontWeightSemibold];
}


@end
