//
//  UIFont+ALTRUUSAdditions.h
//
//  Generated by Zeplin on 6/21/16.
//  Copyright (c) 2016 __MyCompanyName__. All rights reserved. 
//

#import <UIKit/UIKit.h>

@interface UIFont (ALTRUUSAdditions)

+ (UIFont *)altruus_styleMediumFont;

+ (UIFont *)altruus_styleRegularFont;

+ (UIFont *)altruus_menuMediumFont;

+ (UIFont *)altruus_menuSemiBoldFont;

@end
